### ISSUE TITLE
shortcut for "manually-set-ease-factor" in review window

### ISSUE THREAD

**Issue by synog** [AnKing-VIP/manually-set-ease-factor#2]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.54
```

#### Your question
Hello, how can I set a shortcut for "manually-set-ease-factor" that I can use in the review window? There is no shortcut hint visible. Thank you for your help.

**Comment by RisingOrange** [comment]
Sorry, for the late reply. This is now possible. In the review window you can click on the "More" button in the bottom right corner and the last option of the menu that will open should be "Set Ease Factor".
