### ISSUE TITLE
Today's update of the addon caused an error for me. I had to disable it.

### ISSUE THREAD

**Issue by Zeroman123456** [AnKing-VIP/manually-set-ease-factor#3]
I don't know if it's something with my Anki or other people had an issue with today's update of Manually set ease factor addon.

I'm using Anki 2.1.54 Qt5.

This image shows what appears to me when I open Anki while the addon is enabled, I re-installed the addon, but the problem persists, so I had to disable it.Thanks for your efforts.

![image](https://user-images.githubusercontent.com/41925065/202004699-facd7d76-3b78-46ca-9822-a42460e188ce.png)

**Comment by RisingOrange** [comment]
Sorry, that was a mistake on my end. There is a new version of the add-on on AnkiWeb that should not have this problem anymore.
