### ISSUE TITLE
error: add_anking_elements is not defined

### ISSUE THREAD

**Issue by NSBum** [AnKing-VIP/manually-set-ease-factor#4]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [х] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.53
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.53 (96bacf79) Python 3.9.7 Qt 6.3.0 PyQt 6.3.0
Platform: Mac 13.0
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-11-28 14:44:21
Add-ons possibly involved: ⁨Manually Set Ease Factor⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/alan/Library/Application Support/Anki2/addons21/566075556/__init__.py", line 38, in open_ease_edit_window
    EaseEditWindow(cids).exec()
  File "/Users/alan/Library/Application Support/Anki2/addons21/566075556/__init__.py", line 69, in __init__
    self._setup()
  File "/Users/alan/Library/Application Support/Anki2/addons21/566075556/__init__.py", line 112, in _setup
    add_anking_elements(self)
NameError: name 'add_anking_elements' is not defined
```

Looking at your code base, `add_anking_elements()` is not defined anywhere. The add-on functions, of course, if you comment-out that line in `__init__.py`

**Comment by Dangling5061** [comment]
+1

**Comment by AnKingMed** [comment]
@NSBum has this been resolved? Sorry we didn't get to this earlier

**Comment by NSBum** [comment]
No. I commented-out the `add_anking_elements` call:

```
# add_anking_elements(self)
```

and the add-on functions normally. You'll note that it's not defined anywhere in the code base. I wonder what the intent of this function call is...

**Comment by RisingOrange** [comment]
There is now a new version of the add-on on AnkiWeb that doesn't have this problem anymore. I made a mistake in the last update.
